### ISSUE TITLE
Issue with vue-fragment 1.5.2

### ISSUE THREAD

**Issue by sardor01** [Thunberg087/vue-fragment#61]
I'm getting this issue with the new version of vue-fragment (1.5.2):

[Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this [node.](url)
![vue-fragment-error](https://user-images.githubusercontent.com/58367523/109046473-993ee380-76f6-11eb-8eec-8fb46ddd28fa.png)

**Comment by svtokarevsv** [comment]
same. Started happening in 1.5.2. Will revert to previous version for now.

**Comment by elderdog** [comment]
same. Better to roll back to v1.5.1

**Comment by Dylan-bak** [comment]
i have same problem this version has a bug

**Comment by evgencode** [comment]
same problem

**Comment by mschiele** [comment]
same problem here

**Comment by fxmanu** [comment]
Same here. The MR https://github.com/Thunberg087/vue-fragment/pull/48 seems to break having a fragment as a root element in a dynamically added or removed component.  

I rolled back to v1.5.1 and look forward to having fixed this issue in a future release. Thanks for this library :-)

**Comment by victorgarciaesgi** [comment]
Is every one using Nuxt? I have this error since i updated Nuxt to 2.15.x

**Comment by victorgarciaesgi** [comment]
but as @fxmanu said, reverting back to v.1.5.1 fix the problem for me!

**Comment by fxmanu** [comment]
> Is every one using Nuxt? I have this error since i updated Nuxt to 2.15.x

No, I don't.

**Comment by dineshtrivedi** [comment]
Same here. I also rolledback to 1.5.1

**Comment by victorgarciaesgi** [comment]
Ok just to know if it was nuxt related but it seems not!

**Comment by Sardor01** [comment]
> same. Better to roll back to v1.5.1

For now, this seems to solve the problem.

**Comment by korelstar** [comment]
> > same. Better to roll back to v1.5.1
> 
> For now, this seems to solve the problem.

Please keep the issue open since the problem still exists for the latest release. Other people will find this known problem faster.

**Comment by woganmay** [comment]
This caused a production issue for us today. It looks like the bump from 1.5.1 to 1.5.2 introduces a lot more than just backward-compatible bug fixes :)

**Comment by BaileyJM02** [comment]
This is a duplicate of #32.

**Comment by volarname** [comment]
same prob with vue-fragment 1.5.2 and vue 2.6.14

**Comment by yoonwooseong** [comment]
If the occurrence point is a <template>, try wrapping the node in a <div>. I solved it like that

**Comment by alexmccabe** [comment]
@yoonwooseong try wrapping the Node in a. what?

**Comment by Thunberg087** [comment]
Hello everyone, I published a new version ([1.6.0](https://github.com/Thunberg087/vue-fragment/releases/tag/v1.6.0)) that hopefully solves this problem.

**Comment by korelstar** [comment]
> Hello everyone, I published a new version ([1.6.0](https://github.com/Thunberg087/vue-fragment/releases/tag/v1.6.0)) that hopefully solves this problem.

Thanks, but the issue still happens for me with 1.6.0. It only works with 1.5.1.

**Comment by Thunberg087** [comment]
@korelstar How exactly are you using the fragment?

**Comment by korelstar** [comment]
@Thunberg087 It's here: https://github.com/nextcloud/notes/blob/f3fac061860422a98ca002369e146815e059d39f/src/components/NavigationList.vue#L2

**Comment by loehx** [comment]
+1

**Comment by skjnldsv** [comment]
Still occuring unfortunately :/
Using v-if with a computed seems to break it
